name: Docker

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - dev

  release:
    types:
      - published

env:
  DOCKER_BASE_NAME: ghcr.io/slashnephy/rtxalert

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

      - name: Login to Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tag (master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (dev)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DOCKER_TAG=dev" >> $GITHUB_ENV
      - name: Prepare image tag (Release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
